import type { Video, Category, CostItem } from './types';

export const categories: Category[] = [
  { id: '1', name_he: 'תכנון ורישוי', slug: 'planning', description_he: 'מידע על תהליכי תכנון, היתרי בנייה ורישוי', video_count: 45 },
  { id: '2', name_he: 'עלויות ומחירים', slug: 'costs', description_he: 'פירוט עלויות בנייה, מחירונים והשוואות', video_count: 78 },
  { id: '3', name_he: 'שלד ובנייה', slug: 'construction', description_he: 'כל מה שצריך לדעת על שלד הבניין ועבודות בנייה', video_count: 120 },
  { id: '4', name_he: 'חשמל ואינסטלציה', slug: 'electrical', description_he: 'מדריכים לחשמל, אינסטלציה ותשתיות', video_count: 56 },
  { id: '5', name_he: 'גמרים ועיצוב', slug: 'finishing', description_he: 'ריצוף, חיפוי, צבע ועיצוב פנים', video_count: 92 },
  { id: '6', name_he: 'קבלנים ועבודה', slug: 'contractors', description_he: 'בחירת קבלנים, חוזים ופיקוח', video_count: 67 },
  { id: '7', name_he: 'חוקים ותקנות', slug: 'regulations', description_he: 'חוקי בנייה, תקנות ורגולציה', video_count: 34 },
  { id: '8', name_he: 'טיפים כלליים', slug: 'tips', description_he: 'טיפים ועצות כלליות לבונים', video_count: 88 },
];

export const sampleVideos: Video[] = [
  {
    id: '1',
    youtube_id: 'placeholder_1',
    title: 'איך בוחרים קבלן שלד? 10 טיפים שחייבים לדעת לפני שחותמים חוזה',
    duration_seconds: 754,
    category_id: '6',
    category_name: 'קבלנים ועבודה',
    category_slug: 'contractors',
    channel_name: 'הבונה החכם',
    published_at: '2024-03-15',
    thumbnail_url: '/images/placeholder-video.svg',
  },
  {
    id: '2',
    youtube_id: 'placeholder_2',
    title: 'כמה עולה לבנות בית פרטי בישראל ב-2024? פירוט מלא של כל העלויות',
    duration_seconds: 1125,
    category_id: '2',
    category_name: 'עלויות ומחירים',
    category_slug: 'costs',
    channel_name: 'בניה בפרקטיקה',
    published_at: '2024-02-20',
    thumbnail_url: '/images/placeholder-video.svg',
  },
  {
    id: '3',
    youtube_id: 'placeholder_3',
    title: 'תכנון חשמל לבית פרטי - מדריך מקיף למתחילים',
    duration_seconds: 1330,
    category_id: '4',
    category_name: 'חשמל ואינסטלציה',
    category_slug: 'electrical',
    channel_name: 'חשמל ועוד',
    published_at: '2024-01-10',
    thumbnail_url: '/images/placeholder-video.svg',
  },
  {
    id: '4',
    youtube_id: 'placeholder_4',
    title: 'שלבי הבנייה מהיסוד: מהחפירה ועד המפתח - סדר העבודות המלא',
    duration_seconds: 2120,
    category_id: '3',
    category_name: 'שלד ובנייה',
    category_slug: 'construction',
    channel_name: 'הבונה החכם',
    published_at: '2024-04-01',
    thumbnail_url: '/images/placeholder-video.svg',
  },
  {
    id: '5',
    youtube_id: 'placeholder_5',
    title: 'היתר בנייה: כל מה שצריך לדעת על התהליך, המסמכים והזמנים',
    duration_seconds: 955,
    category_id: '1',
    category_name: 'תכנון ורישוי',
    category_slug: 'planning',
    channel_name: 'אדריכלות למתחילים',
    published_at: '2024-03-20',
    thumbnail_url: '/images/placeholder-video.svg',
  },
  {
    id: '6',
    youtube_id: 'placeholder_6',
    title: 'בחירת ריצוף וחיפוי - טעויות נפוצות שכולם עושים וכיצד להימנע מהן',
    duration_seconds: 870,
    category_id: '5',
    category_name: 'גמרים ועיצוב',
    category_slug: 'finishing',
    channel_name: 'עיצוב הבית',
    published_at: '2024-02-05',
    thumbnail_url: '/images/placeholder-video.svg',
  },
];

export const sampleCosts: CostItem[] = [
  { item: 'חפירה ויסודות', price: 150000, unit: 'פאושלי', context: 'בית 180 מ"ר' },
  { item: 'שלד בטון', price: 280000, unit: 'פאושלי', context: 'כולל עבודה וחומרים' },
  { item: 'טיח חוץ', price: 120, unit: 'מ"ר', context: 'כולל חומרים' },
  { item: 'ריצוף', price: 180, unit: 'מ"ר', context: 'לא כולל חומר' },
  { item: 'חשמל', price: 45000, unit: 'פאושלי', context: 'בית סטנדרטי' },
  { item: 'אינסטלציה', price: 35000, unit: 'פאושלי', context: '3 חדרי רחצה' },
];
